<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Batch038MathCheck</AssemblyName>
    <RootNamespace>Batch038MathCheck</RootNamespace>
  </PropertyGroup>
</Project>
