<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Batch034TranspilerDebug</AssemblyName>
    <RootNamespace>Batch034TranspilerDebug</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>D:\GGGGG\K1515\smapi-internal\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Stardew Valley">
      <HintPath>D:\GGGGG\K1515\Stardew Valley.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
